import type { LegalSection } from "./LegalPage";

export const LEGAL_UPDATED = "September 3, 2026";

export const privacySections: LegalSection[] = [
  { title: "Information we collect", paragraphs: ["We collect account information, project website URLs, scan configuration, audit findings, usage records, support communications, and technical data needed to operate and secure Scanlyst."], items: ["Account details such as name, email address, authentication events, and preferences.", "Website targets, scan results, findings, evidence, remediation notes, schedules, and report settings.", "Service telemetry such as IP address, browser type, device information, timestamps, logs, and security events.", "Subscription status and billing identifiers. Payment card details are processed by Dodo Payments and are not stored directly by Scanlyst."] },
  { title: "How we use information", items: ["Provide, maintain, troubleshoot, and improve the service.", "Run authorized scans, generate reports, monitor usage limits, and deliver requested alerts.", "Authenticate users, prevent abuse, investigate incidents, and protect our infrastructure.", "Process subscriptions, provide support, and send operational communications.", "Comply with legal obligations and enforce our agreements."] },
  { title: "Service providers", paragraphs: ["We use carefully selected providers for infrastructure, payments, transactional email, monitoring, and analytics. They may process data only to provide contracted services and subject to their own security and privacy commitments."], items: ["Dodo Payments for checkout, subscription administration, tax handling, and payment records.", "Resend or another configured email provider for account and service messages.", "Cloud hosting, database, logging, and monitoring providers used to operate Scanlyst."] },
  { title: "Website scanning data", paragraphs: ["Scanlyst processes public website content and any credentials or integration secrets you intentionally provide for an authorized scan. Sensitive configuration is encrypted where supported and is restricted to the scan workflow. Do not submit credentials or data you are not authorized to use."] },
  { title: "Retention and deletion", paragraphs: ["We retain account and scan data while your account is active and as reasonably necessary for service delivery, security, dispute resolution, and legal compliance. You may request account deletion. Some records may remain in backups or be retained where required by law, fraud prevention, or financial reporting obligations."] },
  { title: "Security", paragraphs: ["We use administrative, technical, and organizational safeguards designed to protect personal data. No online service can guarantee absolute security. You are responsible for protecting your account credentials and promptly reporting suspected compromise."] },
  { title: "Your choices and rights", paragraphs: ["Depending on your location, you may have rights to access, correct, export, restrict, object to processing of, or delete personal information. You may also withdraw consent where consent is the legal basis for processing. Contact us to exercise a request; we may verify your identity before responding."] },
  { title: "International processing", paragraphs: ["Scanlyst and its providers may process information in countries other than your own. Where required, we use appropriate safeguards for international data transfers."] },
  { title: "Children", paragraphs: ["Scanlyst is intended for business users and is not directed to children under 16. We do not knowingly collect personal information from children."] },
  { title: "Changes to this policy", paragraphs: ["We may update this policy as the service, laws, or our practices change. Material changes will be communicated through the service or by email when appropriate."] },
];

export const termsSections: LegalSection[] = [
  { title: "Agreement", paragraphs: ["By creating an account, purchasing a subscription, or using Scanlyst, you agree to these Terms of Service and the policies incorporated by reference. If you use Scanlyst for an organization, you represent that you are authorized to bind that organization."] },
  { title: "Authorized use only", paragraphs: ["You may scan only websites, applications, APIs, infrastructure, accounts, and repositories that you own or for which you have explicit authorization to test. Scanlyst is not permission to test a third party. You are responsible for obtaining and retaining evidence of authorization."], items: ["Do not use Scanlyst to gain unauthorized access, disrupt services, extract data, evade controls, or harm another person.", "Do not submit production credentials unless the relevant workflow explicitly requires them and you understand the associated risk.", "Follow applicable laws, provider terms, rate limits, and coordinated disclosure practices."] },
  { title: "Accounts", paragraphs: ["You must provide accurate information, protect your credentials, and promptly notify us of unauthorized access. You are responsible for activity performed through your account and API keys."] },
  { title: "Subscriptions and billing", paragraphs: ["Paid plans renew for the selected billing period until cancelled. Prices, taxes, limits, and included features are presented at checkout. Dodo Payments processes payments and may act as merchant of record. Cancellation stops future renewal but does not automatically refund the current period except where required by law or stated in our Refund Policy."] },
  { title: "Scan results and professional advice", paragraphs: ["Scanlyst provides automated signals and remediation guidance. Results may contain false positives, false negatives, incomplete coverage, or outdated information. Scanlyst does not replace a qualified penetration test, legal review, accessibility audit, compliance certification, or professional security assessment."] },
  { title: "Availability and changes", paragraphs: ["We may modify features, limits, integrations, or the service to improve security and reliability. We may suspend access for maintenance, abuse prevention, nonpayment, legal requirements, or risk to the service or others."] },
  { title: "Customer content", paragraphs: ["You retain ownership of data you submit. You grant Scanlyst the limited rights necessary to host, process, transmit, and display that data to provide and secure the service. You represent that you have all rights and permissions required for the data and targets you provide."] },
  { title: "Intellectual property", paragraphs: ["Scanlyst, its software, branding, documentation, and service design are protected by intellectual property laws. These terms provide a limited, revocable, non-transferable right to use the service; they do not transfer ownership."] },
  { title: "Disclaimers and liability", paragraphs: ["The service is provided on an as-available basis to the extent permitted by law. We disclaim implied warranties where legally permitted. To the maximum extent permitted by law, Scanlyst will not be liable for indirect, incidental, special, consequential, exemplary, or lost-profit damages arising from use of the service."] },
  { title: "Termination", paragraphs: ["You may stop using the service at any time. We may suspend or terminate access for material breach, unlawful activity, abuse, security risk, or nonpayment. Provisions that by their nature should survive termination will remain in effect."] },
  { title: "Changes and contact", paragraphs: ["We may revise these terms and will provide reasonable notice of material changes. Continued use after the effective date constitutes acceptance where permitted by law."] },
];

export const cookieSections: LegalSection[] = [
  { title: "How Scanlyst uses cookies", paragraphs: ["Scanlyst uses cookies and similar browser storage to keep users signed in, protect sessions, remember the active project, preserve preferences, and understand whether the service is operating correctly."] },
  { title: "Essential cookies", items: ["Authentication cookies used to maintain secure access and refresh sessions.", "Security cookies used for request integrity, fraud prevention, and abuse detection.", "Preference storage used to remember the active project and interface choices."] },
  { title: "Analytics and optional technologies", paragraphs: ["If optional analytics or marketing technologies are introduced, we will update this policy and request consent where required. The current application should not load non-essential tracking before the required consent choice is available."] },
  { title: "Managing cookies", paragraphs: ["You can delete or block cookies through your browser settings. Blocking essential cookies may prevent login, billing, project selection, and other core functionality from working."] },
  { title: "Retention", paragraphs: ["Session cookies expire when the session ends or at their configured expiration. Persistent preference and security cookies remain for a limited period unless you remove them earlier."] },
];

export const acceptableUseSections: LegalSection[] = [
  { title: "Permitted purpose", paragraphs: ["Scanlyst is designed for defensive security, quality assurance, compliance review, monitoring, and remediation of systems you are authorized to assess."] },
  { title: "Prohibited activity", items: ["Scanning or testing systems without explicit authorization.", "Attempting denial of service, destructive exploitation, credential theft, malware delivery, spam, phishing, or data exfiltration.", "Circumventing plan limits, access controls, rate limits, or safety mechanisms.", "Using findings to exploit, extort, harass, discriminate, or cause harm.", "Reselling access or reports in violation of your plan or misrepresenting automated results as a certification."] },
  { title: "Operational safeguards", paragraphs: ["You must choose safe testing windows, use designated test accounts where appropriate, protect secrets, respect target capacity, and stop a scan if it may cause instability. Production testing remains your responsibility."] },
  { title: "Enforcement", paragraphs: ["We may throttle, pause, investigate, or terminate activity that appears unauthorized, abusive, unlawful, or harmful. We may preserve and disclose relevant records where legally required or necessary to protect people and systems."] },
];

export const refundSections: LegalSection[] = [
  { title: "Subscriptions", paragraphs: ["You may cancel renewal at any time through the billing portal. Cancellation takes effect at the end of the current paid billing period unless applicable law requires otherwise."] },
  { title: "Refund requests", paragraphs: ["Except where required by law, completed billing periods and consumed usage are generally non-refundable. If you were charged because of a confirmed billing error, duplicate transaction, or service failure that materially prevented use, contact us within 14 days of the charge with the account email and transaction reference."] },
  { title: "Trials and plan changes", paragraphs: ["Trial eligibility and plan-change credits are shown at checkout or in the billing portal. Upgrades may take effect immediately; downgrades generally take effect at the next renewal."] },
  { title: "Payment disputes", paragraphs: ["Please contact support before initiating a payment dispute so we can investigate promptly. Nothing in this policy limits mandatory consumer rights that apply in your jurisdiction."] },
];

export const disclosureSections: LegalSection[] = [
  { title: "Reporting a vulnerability", paragraphs: ["Send a concise report to security@scanlyst.dev with the affected URL or component, reproduction steps, impact, and any supporting evidence. Do not include secrets or personal data unless necessary; use encrypted communication when available."] },
  { title: "Safe-harbor expectations", items: ["Make a good-faith effort to avoid privacy violations, data destruction, service disruption, and access beyond what is needed to demonstrate the issue.", "Do not use denial-of-service testing, social engineering, physical attacks, automated high-volume scanning, or third-party compromise.", "Give us reasonable time to investigate and remediate before public disclosure.", "Stop testing and notify us if you encounter sensitive data or unexpected access."] },
  { title: "Our response", paragraphs: ["We aim to acknowledge actionable reports, investigate them, and communicate material progress. We do not currently promise monetary rewards. Eligibility for recognition is determined case by case."] },
  { title: "Scope", paragraphs: ["Testing is limited to Scanlyst-controlled systems. Customer websites, third-party services, social engineering, and vendor infrastructure are outside scope unless we explicitly confirm otherwise in writing."] },
];
