import type { Metadata } from "next";
import { Geist_Mono, Marcellus, DM_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "../base-component/NavBar";
import { TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "react-hot-toast";
// import Navbar from "@/base-component/NavBar";

const fontHeading = Marcellus({
  variable: "--font-heading",
  subsets: ["latin"],
  weight:"400"
});

const fontContent = DM_Sans({
  variable: "--font-content",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});





const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});





export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${fontHeading.variable} ${fontContent.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <TRPCReactProvider>
        {children}
        <Toaster position="top-right" toastOptions={{ duration: 4000 }} />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
